### ISSUE TITLE
[WARN] 13:03:02.329 Expected 'interior' attribute but found none.

### ISSUE THREAD

**Issue by edeso** [openjump-gis/openjump#37]
hey Mike,

are these warning really necessary? 

```
[WARN] 13:03:02.329 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.331 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.334 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.336 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.339 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.341 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.343 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.345 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.347 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.348 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.350 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.352 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.354 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.356 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.358 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.362 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.365 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.367 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.369 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.371 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.373 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.375 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.377 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.379 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.381 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="2"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.384 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="2"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.386 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="2"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.388 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="2"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)

**Comment by mukoki** [comment]
Hi Ede,Not very interesting, I give you that. I think it should be solved by an improvement of XML2java rather than just eliminating the warning though.There is a ticket for that :#518 Java2xml framework : no default default valueThere maybe another way. I think warnings are systematically emitted because there are some predefined symbology stored somewhere in the code and not using the new 'interior' tag. It should be possible to upgrade these predefined symbols so that they do not emit warnings anymore. Michaëlenvoyé : 26 juillet 2021 à 13:06de : edeso ***@***.***>à : openjump-gis/openjump ***@***.***>cc : Subscribed ***@***.***>objet : [openjump-gis/openjump] [WARN] 13:03:02.329 Expected 'interior' attribute but found none. (#37) hey Mike,are these warning really necessary?[WARN] 13:03:02.329 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.331 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.334 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.336 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.339 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.341 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.343 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.345 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.347 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.348 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.350 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.352 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.354 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.356 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.358 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.362 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="4"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.365 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.367 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.369 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.371 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.373 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.375 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.377 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.379 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="1"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.381 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="2"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.384 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="2"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.386 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="2"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)
[WARN] 13:03:02.388 Expected 'interior' attribute but found none. Tag = line; Attributes = [Attribute: enabled="true"], [Attribute: width="2"] at com.vividsolutions.jump.util.java2xml.XML2Java$1.attributeSpecFound(XML2Java.java:147)

**Comment by edeso** [comment]
@mukoki can you be a bit more specific? 
1. why exactly is this warning printed anyway, if the attribute seems not to be needed anyway? 
2. what are the mentioned hacks "to assure backward compatibility" in https://sourceforge.net/p/jump-pilot/bugs/518/

**Comment by mukoki** [comment]
Ede,Currently, the XML2Java framework does not accept "optional" attributes. If an attribute is defined in the java2xml config file, it must be there or it throws an exception.To avoid the exception in the case of "interior" attribute (and some others), there are hacks in the code which hide exceptions for these specific attributes. It works and it makes these attributes optional, but the solution is not clean (not extendable) and my idea was to introduce the capability of having optional attributes (or elements ?) in the config files (java2xml). Anyway, we can keep or remove the message. I don't pretend it is interesting for the user. It is just a reminder that there is something to improve in the java2xml framework to fully accept this kind of attribute and maintain backward compatibility.Michaël    envoyé : 27 juillet 2021 à 14:13de : edeso ***@***.***>à : openjump-gis/openjump ***@***.***>cc : Michaël Michaud ***@***.***>, Mention ***@***.***>objet : Re: [openjump-gis/openjump] [WARN] 13:03:02.329 Expected 'interior' attribute but found none. ***@***.*** can you be a bit more specific?why exactly is this warning printed anyway, if the attribute seems not to be needed anyway?what are the mentioned hacks "to assure backward compatibility" in https://sourceforge.net/p/jump-pilot/bugs/518/—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by edeso** [comment]
Mike,

quickly debugged into it and the Warning seems to come from reading `AbstractPalettePanel.xml` creating a BasicStyleList, but can't figure out how the values are mapped to java members, as the names seem not to be reflected in BasicStyle. can you give me a lil more background?

..ede

**Comment by edeso** [comment]
@mukoki needs to be thoroughly debugged it seems. i'm pretty sure we can decorate members or add some other way to a class to mark voluntary attributes.
