### ISSUE TITLE
Open a GeoTIFF via Commons Imaging doesn't read geoTags

### ISSUE THREAD

**Issue by ma15569** [openjump-gis/openjump#75]
com.vividsolutions.jump.workbench.imagery.graphic.CommonsImage is suited to read only worldfiles.

**Comment by edeso** [comment]
Commons Imaging Readers always read the full image to memory. it is mainly there as an alternative, to try out if other readers fail. it has not GeoTIFF support as such build in a such right now. that's why it is prioritized to the bottom of the list.

GeoTIFFs should be read with one of the better performing ImageIO-ext,JAI readers which support several ways to determine the reference system.

**Comment by ma15569** [comment]
Hi Ede,
ImageIO-ext is definitively the right aternative for GeoTIFF. My question was in the case that some user should try to use Commons to read GeoTiff. Anyghow I am happy with GeoTIFF.
